name = "uptimeflare"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "cd0e4e20-fd7a-45c8-8e26-f134bec945f5"
