name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "cd0e4e20-fd7a-45c8-8e26-f134bec945f5"

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteChecker"]

[triggers]
crons = ["* * * * *"]
